"""Convert supply fields to BigInteger

Revision ID: 1d587ca9726c
Revises: 5f61d493481b
Create Date: 2025-05-27 13:57:26.046201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d587ca9726c'
down_revision: Union[str, None] = '5f61d493481b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('crypto_metadata', 'circulating_supply',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    schema='reporting_schema'
                    )
    op.alter_column('crypto_metadata', 'max_supply',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    schema='reporting_schema'
                    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
